<?php

namespace MoviesBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpMovies()
    {
        $movies = $this->findBy([],["rating" => 'DESC'],50);
        return $movies;
    }
}
