<?php

namespace MoviesBundle\Repository;

use MoviesBundle\Form\ReviewType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpMovies($page)
    {
        $a = ($page -1 ) * 18;
        $movies = $this->findBy([],["rating" => 'DESC'],18, $a);
        return $movies;
    }
    public function findUpAllMovies()
    {
        $movies = $this->findBy([],["rating" => 'DESC']);
        return $movies;
    }
    public function countByAccount()
    {
        $qb = $this->createQueryBuilder('e');

        $qb ->select($qb->expr()->count('e'));

        return (int) $qb->getQuery()->getSingleScalarResult();
    }

}
