<?php

namespace MoviesBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpAllReview()
    {
        $reviews = $this->findBy([],["film" => 'DESC']);
        return $reviews;
    }

}
