security:
    firewalls:
        main: # <-- nom du firewall
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                 path: logout
                 target: movies_homepage

    providers:
        main_provider:
            entity:
                class:    MoviesBundle:User
                property: username

    encoders:
        NantesBundle\Entity\User:
            algorithm: bcrypt
            cost: 10

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
