movies_homepage:
    path:     /
    defaults: { _controller: MoviesBundle:Movies:index }
detailMovies:
    path:     /detail/{id}
    defaults: { _controller: MoviesBundle:Movies:detail }
AdminMovies:
    path:     /admin/gestion-des-films
    defaults: { _controller: MoviesBundle:AdminMovies:gestion }
CreatedMovies:
    path:     /admin/creation-de-film
    defaults: { _controller: MoviesBundle:AdminMovies:create }
editMovies:
    path:     /modification/{id}
    defaults: { _controller: MoviesBundle:AdminMovies:edit }


