movies_homepage:
    path:     /
    defaults: { _controller: MoviesBundle:Movies:index }
detailMovies:
    path:     /detail/{id}
    defaults: { _controller: MoviesBundle:Movies:detail }
    requirements:
              id: '\d+'
AdminMovies:
    path:     /admin/gestion-des-films
    defaults: { _controller: MoviesBundle:AdminMovies:gestion }
